<a href="https://colab.research.google.com/github/Bantyrajpuana/python-tutorial/blob/main/dev/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
numpy is python libaray.<br>
numpy called numerical python.<br>
numpy is used to working with array.<br>
it was created in 2005 by travis oliphant.it is an open source project it is used eaisly.<br>
it also has function for working domain of linear algebra, fourier transformand matrices.<br>
numpy always be written in python.<br>

# why use numpy
in python we have list that serve the purpose of array .but they are slow to process.
numpy aims to provide an array object that is up to fa



In [ ]:

# numpy example
import numpy as np
arr=np.array([1,3,4,5,6,7,9])
print(arr)
print(type(arr))

[1 3 4 5 6 7 9]
<class 'numpy.ndarray'>


<h1>Dimension in array<h1>
a dimension in array is one level of array depth (nested array (nested array are array that have array as their element ))

<h2>0-d array<h2>
0-d array or scalarare the element in an array ,each value in an array is a 0-d array..

<h3>1-d array <h3>
an array that has a 0-d array as its element called unidemensional array or 1-d array..

<h4>2-d array<h4>

<h4>3-d array<h4>

In [ ]:
import numpy as np
arr0d=np.array(44)
print(arr0d)
print(arr0d.ndim)

44
0


In [ ]:
import numpy as np
arr1d=np.array([44,34,45,52,5,2,2])
print(arr1d)
print(arr1d.ndim)

[44 34 45 52  5  2  2]
1


In [ ]:
import numpy as np
arr2d=np.array([[44,33,55],[22,33,44]])
print(arr2d)
print(arr2d.ndim)

[[44 33 55]
 [22 33 44]]
2


In [ ]:
import numpy as np
arr3d=np.array([[[33,34,556,44,7],[33,55,66,66,66],[22,444,55,66,66677]]])
print(arr3d)
print(arr3d.ndim)

[[[   33    34   556    44     7]
  [   33    55    66    66    66]
  [   22   444    55    66 66677]]]
3


In [ ]:
import numpy as np
arr=np.array([33,34,556,44,7], ndmin=32)
print(arr)
print('num of dim ; ',arr.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 33  34 556
                                 44   7]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
num of dim ;  32


In [ ]:
import numpy as np
arr=np.array([33,34,556,44,7])
print(arr[4])
print(arr[4]-arr[2])

7
-549


In [ ]:
import numpy as np
arr=np.array([[33,34,556,44,7],[33,33,22,11,22]])
print(arr[1])
print('location',arr[1,3])
ind=np.nonzero(arr)
print(ind[0])
print('location',33)

[33 33 22 11 22]
location 11
[0 0 0 0 0 1 1 1 1 1]
location 33
